---
- name:  set up vpn prerequisites
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: {% raw %}"{{ item }}"{% endraw %}
      with_items:
        - ../../account/vars.yml
        - env.yml
      tags: always

  roles:
    - reactiveops.vpn-stack

- name: configure vpn instance
  hosts: tag_Layer_vpn_public_ip
  become: yes
  become_user: root

  pre_tasks:
    - include_vars: {% raw %}"{{ item }}"{% endraw %}
      with_items:
        - ../../account/vars.yml
        - env.yml

  roles:
    - role: Stouts.openvpn-master
      vpn_role: 'primary'
      org: {% raw %}"{{ org_name }}"{% endraw %}
      openvpn_first_run: {% raw %}"{{ hostvars['localhost']['openvpn_first_run'] }}"{% endraw %}
