apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: docker-gc
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: docker-gc
      name: docker-gc
    spec:
      containers:
      - image: quay.io/reactiveops/docker-gc:master
        imagePullPolicy: Always
        name: docker-gc
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
          - name: FREQUENCY
            value: "7200"
          - name: EXCLUDE_FROM_GC
            valueFrom:
              configMapKeyRef:
                name: docker-gc
                key: exclude-from-gc
          - name: EXCLUDE_CONTAINERS_FROM_GC
            valueFrom:
              configMapKeyRef:
                name: docker-gc
                key: exclude-containers-from-gc
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket
          - mountPath: /etc/config
            name: excludes
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: excludes
          configMap:
            name: docker-gc
            items:
              - key: image-excludes.file
                path: docker-gc-exclude
              - key: container-excludes.file
                path: docker-gc-exclude-containers
      dnsPolicy: Default
