kind: ConfigMap
apiVersion: v1
metadata:
  name: docker-gc
  namespace: kube-system
data:
  image-excludes.file: |-
    kube-
  container-excludes.file: |-
    kube-system
  exclude-from-gc: '/etc/config/docker-gc-exclude'
  exclude-containers-from-gc: '/etc/config/docker-gc-exclude-containers'
